### ISSUE TITLE
Production deployment broken

### ISSUE THREAD

**Issue by icarito** [publiclab/mapknitter#1338]
Seems like we've misconfigured the database variables for production.

Trying to deploy today:
```
puma.1      | ! Unable to load application: ActiveRecord::AdapterNotSpecified: '$_RAILS_ENV' database is not configured. Available: ["default"
, "development", "production", "test"]                                                                                   
puma.1      | /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/connection_specification.rb:260:in `resolve_s$
mbol_connection': '$_RAILS_ENV' database is not configured. Available: ["default", "development", "production", "test"] (ActiveRecord::Adapte$
NotSpecified)                                                                                                                  
puma.1      |   from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/connection_specification.rb:241:in `re$
olve_connection'                                                                                                                              
puma.1      |   from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/connection_specification.rb:143:in `re$
olve'                                                                                                                            
puma.1      |   from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_handling.rb:57:in `establish_connection'        
```

**Comment by alaxalves** [comment]
Probably the RAILS_ENV variable has not been set.

**Comment by jywarren** [comment]
Hi, was this resolved, just checking! Thank you!!

**Comment by icarito** [comment]
Oh hi, no, I'm afraid. I'll take a look now.

**Comment by jywarren** [comment]
Ah, it looks like we created a new `RAILS_ENV` var here, maybe we have to create that in Jenkins or in production container too?

https://github.com/publiclab/mapknitter/pull/1329/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R69

It's just set up for Travis.

**Comment by icarito** [comment]
I think this was resolved, the issue with deploying was fixed with https://github.com/publiclab/mapknitter/pull/1428 - so this should autodeploy already! Sorry this was left open.
