### ISSUE TITLE
Add to README how to setup or disable Amazon S3

### ISSUE THREAD

**Issue by icarito** [publiclab/mapknitter#245]
### What happened just before the problem occurred

Trying to get staging instance running, found hidden exception:

```
Errno::ENOENT (No such file or directory @ rb_sysopen - config/amazon_s3.yml):                                                                                                   
  app/controllers/images_controller.rb:51:in `block in create'                                                                                                                   
  app/controllers/images_controller.rb:50:in `create'                                                                                                                            
```

**Comment by icarito** [comment]
Found relevant config bits in `config/initializers/paperclip.rb`

**Comment by icarito** [comment]
This issue shows up only when attempting to put MK in production.
