### ISSUE TITLE
second page of / paginated maps broken

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#55]
@patcyole sez: I also got this when I tried to move to next page, going to page 3:

<pre>
TypeError in Maps#index
Showing /home/warren/mapknitter2/app/views/maps/index.html.erb where line #62 raised:
wrong argument type nil (expected String)
Extracted source (around line #62):
59: | <%= map.location %>
60: </small></p>
61: <p class="description"><small>
62: <%=raw truncate(markdown_to_html(map.description),:length =>200) %>
63: <% if !map.description %><i>no description</i><% end %>
64: </small>
65: </p>
Rails.root: /home/warren/mapknitter2
Application Trace | Framework Trace | Full Trace
app/helpers/map_helper.rb:5:in `to_html'
app/helpers/map_helper.rb:5:in `markdown_to_html'
app/views/maps/index.html.erb:62:in `block in _app_views_maps_index_html_erb__2959561373103988946_28118360'
app/views/maps/index.html.erb:41:in `_app_views_maps_index_html_erb__2959561373103988946_28118360'
app/controllers/maps_controller.rb:11:in `index'
Request
Parameters:
{"page"=>"3"}
Show session dump
Show env dump
Response
Headers:
None
</pre>

![mapknitter2 issues screenshots images export_page_4](https://cloud.githubusercontent.com/assets/5530305/5889689/de457b20-a3e8-11e4-9d2d-1ec74121c315.jpg)

**Comment by jywarren** [comment]
fixed! will be pushed to testing server soon
