### ISSUE TITLE
Export bug (during deployment) - map pages don't load during exports

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#596]
@icarito and I are deploying a new version of MapKnitter and keep seeing this series of events:

1. start an export (as non-logged-in user)
2. during export, the map page doesn't load, with a 500 error but no log output (example: https://mapknitter.org/maps/test-mtwapa-creek)
3. when map completes export, the map page loads again
4. if the export is interrupted, the map page never loads

Also, all other pages on the site work fine even when one page doesn't load.

### Reproducibility

I've been able to (i think) reproduce this locally! See my console output below, with the `core dumped` message that makes me think this was it (maybe accounts for no log output):

```
Rendered layouts/knitter2.html.erb (377.1ms)
Completed 500 Internal Server Error in 463.4ms (ActiveRecord: 28.3ms)


Started GET "/assets/application.js?body=1" for 127.0.0.1 at 2019-05-13 19:38:36 -0400


Started GET "/assets/jquery-ujs/src/rails.js?body=1" for 127.0.0.1 at 2019-05-13 19:38:36 -0400


Started GET "/assets/style.css?body=1" for 127.0.0.1 at 2019-05-13 19:38:36 -0400


Started GET "/assets/application.css?body=1" for 127.0.0.1 at 2019-05-13 19:38:36 -0400
App 6400 output: Aborted (core dumped)
App 6400 output: convert +antialias -size 29963x29963  xc:none -draw "fill black stroke red stroke-width 30 polyline 0,0 29963,0 29963,15287 0,15287 0,0"  -alpha set -channel A -transparent red -blur 0x8 -channel R -evaluate set 0 +channel public/warps/test/1-mask.png
App 6400 output: Aborted (core dumped)
App 6400 output: composite public/warps/test/1-mask.png public/warps/test/1.png -compose DstIn -alpha Set public/warps/test/1-masked.png
App 6400 output:


Started GET "/assets/junction/webfonts/junction-light.woff" for 127.0.0.1 at 2019-05-13 19:38:36 -0400
App 6400 output: composite: unable to open image `public/warps/test/1-mask.png': No such file or directory @ error/blob.c/OpenBlob/2712
App 6400 output: .
App 6400 output: composite: unable to open image `public/warps/test/1.png': No such file or directory @ error/blob.c/OpenBlob/2712
App 6400 output: .
App 6400 output: composite: missing an image filename `public/warps/test/1-masked.png' @ error/composite.c/CompositeImageCommand/1613
App 6400 output: .
App 6400 output: gdal_translate -of GTiff -a_srs EPSG:4326  -gcp 0.0, 0.0, -71.547088623, 41.8751851185 -gcp 29963.315076660695888888888888888888888888888888889, 0.0, -71.277923584, 41.8751851185 -gcp 29963.315076660695888888888888888888888888888888889, 15287.405647381209, -71.277923584, 41.7728479819 -gcp 0.0, 15287.405647381209, -71.547088623, 41.7728479819  -co "TILED=NO" public/warps/test/1-masked.png public/warps/test/1-geo-unwarped.tif
App 6400 output: ERROR 4: `public/warps/test/1-masked.png' does not exist in the file system,
App 6400 output: and is not recognised as a supported dataset name.
App 6400 output:
App 6400 output: GDALOpen failed - 4
App 6400 output: `public/warps/test/1-masked.png' does not exist in the file system,
```

**Comment by jywarren** [comment]
Yes, I can change the export status to `warping 1 of 1` manually in the console and then the map page doesn't load.

**Comment by jywarren** [comment]
Even better. I can set `export.running?` to return `true` and that causes the map page to 500

**Comment by jywarren** [comment]
And noting that actually locally i'm on Ruby 2.4.4, so I don't think it's a Ruby version number issue vs. 2.4.6

**Comment by jywarren** [comment]
yep, this line:

https://github.com/publiclab/mapknitter/blob/3d25dc7bdaff774b4ae256ea98d0a71f2d70a11b/app/views/maps/_sidebar_exports.html.erb#L50

```
> ((@map.exports.last.updated_at - DateTime.now) / 1.hours) > 4
  Export Load (0.3ms)  SELECT `exports`.* FROM `exports` WHERE `exports`.`map_id` = 1 ORDER BY `exports`.`id` DESC LIMIT 1
TypeError: ActiveSupport::Duration can't be coerced into Float
        from (irb):8:in `/'
        from (irb):8
        from /home/warren/.rvm/gems/ruby-2.4.4/gems/railties-3.2.22.5/lib/rails/commands/console.rb:47:in `start'
        from /home/warren/.rvm/gems/ruby-2.4.4/gems/railties-3.2.22.5/lib/rails/commands/console.rb:8:in `start'
        from /home/warren/.rvm/gems/ruby-2.4.4/gems/railties-3.2.22.5/lib/rails/commands.rb:41:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

**Comment by jywarren** [comment]
Fixed in https://github.com/publiclab/mapknitter/commit/3b50d1f1b42d622a0d9988279ee56d5e1695fc5f - testing on jenkins unstable
