### ISSUE TITLE
Cache issues (bower cache) in configuration

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#812]
We just saw Stable fail to build due to a cache issue with this error: https://jenkins.laboratoriopublico.org/job/Mapknitter-Stable/193/console

```
[1Bdocker-compose exec -T web bash -l -c "sleep 10 && rake db:migrate && rake assets:precompile"
mesg: ttyname failed: Inappropriate ioctl for device
rake aborted!
Errno::ENOENT: No such file or directory @ rb_file_s_stat - /app/public/lib/cartagen/api/resources/images/default/grid/hmenu-desc.gif
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:16:in `stat'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:16:in `stat'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:18:in `block in initialize'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:41:in `stat'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:211:in `block in stat_directory'
```

Connecting this maybe to https://github.com/publiclab/mapknitter/pull/794 cc @alaxalves @icarito (we're working on a deployment to live right now)

**Comment by sashadev-sky** [comment]
Yarn didn't update LDI from `0.6.0` to `0.7.6` might be relevant

**Comment by jywarren** [comment]
Yes, actually let's make a new issue as this seems unrelated enough. Thanks, Sasha!

**Comment by jywarren** [comment]
Actually merging with #791...! Thanks!
